services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: apppwd
    ports:
      - "3307:3306"
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papppwd"]
      interval: 5s
      retries: 30

  api:
    build: 
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Default: "server=db;port=3306;database=appdb;user=app;password=apppwd;TreatTinyAsBoolean=false"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080   
    environment:
      - VITE_API_BASE_URL=http://localhost:8080    
    depends_on:
      - api
    ports:
      - "5173:80" 

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
